version: '3.8'
name: image-caching-server-nodejs

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - nodejs
    restart: unless-stopped
    networks:
      - frontend_network

  nodejs:
    image: node:22-alpine
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
      - ./logs/nodejs/:/usr/src/app/storage/logs
      - ./image:/usr/src/app/storage/image
    command: [ "sh", "-c", "npm install && npx pm2-runtime start app.json" ]
    environment:
      NODE_ENV: development
      # DOMAIN: img.joball.tw
    restart: unless-stopped
    networks:
      - frontend_network

networks:
  frontend_network:
    driver: bridge
